name: Update Go Game

on:
  issue_comment:
    types: [created]

jobs:
  update-board:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Get comment text
        id: get_comment
        run: |
          echo "##[set-output name=comment;]${{ github.event.comment.body }}"

      - name: Update board with new move
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/update_board.py "${{ steps.get_comment.outputs.comment }}"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add board.svg
          git commit -m "Update board with new move"
          git push
